### ISSUE TITLE
Blocking hCaptcha

### ISSUE THREAD

**Issue by amuagarwal** [NopeCHA/NopeCHA#20]
The update is blocking hCaptcha and not allowed user to open image dialog on checkbox click. In developer console always give error "Could not establish connection. Receiving end does not exist."

Everything works fine as soon as disabled the extension. 

This is the only update installed in Brave with in-built ad-blocker

**Comment by Le0Developer** [comment]
Can't reproduce.

**Comment by amuagarwal** [comment]
![image](https://user-images.githubusercontent.com/7331483/198988865-0c85cd35-c415-4532-9ee6-336423924eae.png)
this is what i am getting on every site where ever hCaptcha is there

**Comment by Le0Developer** [comment]
What version of the extension are you using?

**Comment by amuagarwal** [comment]
v 0.2.3

**Comment by Le0Developer** [comment]
Upgrade to [v0.2.4, v0.2.5 or v0.3.0](https://github.com/NopeCHA/NopeCHA/releases).
Chrome webstore has not yet approved the update, so you need to install the crx from the releases.

**Comment by amuagarwal** [comment]
Oki let me try

**Comment by k290** [comment]
Those errors occur when you've run out of free credits. Wait for your credits to replenish and it should work again.

**Comment by NopeCHA** [comment]
Those errors are not caused by the extension. It seems that no one else is able to reproduce your issue. Reinstall your browser.
