### ISSUE TITLE
Discord?

### ISSUE THREAD

**Issue by lgamerlive** [NopeCHA/NopeCHA#25]
So uhh I think the discord got termed are you guys planning on making a new one?

**Comment by fmbcccc** [comment]
what happened? discord channel disappeared?

**Comment by awaprimPL** [comment]
is discord gonna come back?

**Comment by Juicpt** [comment]
@Jaewan-Yun 
is discord gonna come back?

**Comment by k290** [comment]
Discord also gone for me

**Comment by gugacarmellino** [comment]
I'm a customer and also need help. what other channel can I get support?

**Comment by saad1430** [comment]
bye bye discord??

**Comment by lgamerlive** [comment]
https://github.com/NopeCHA/NopeCHA/issues/26
