### ISSUE TITLE
avoid google login

### ISSUE THREAD

**Issue by test2a** [NopeCHA/NopeCHA#28]
Hi.

just discovered your website. looks nice enough. i actually used your extension before but now i am in the market for an api service which you also offer. cool but the problem is you only have google login.

i do NOT have a google account. would it be possible for you to set me up manually so i can avoid that? i am interested in the claimed 1.2S of simple image captcha.

also a question, i have used other websites but they too don't have  a way to detect if the text is in capitals or not or a way to pass an argument for capitals or numbers only?

**Comment by NopeCHA** [comment]
> i do NOT have a google account
You can create one on google.com

**Comment by test2a** [comment]
@NopeCHA is your api compatible with other captcha api services?
like 

https://2captcha.com/2captcha-api
https://azcaptcha.com/document
https://learn.captcha.guru/#/

like can i replace their api url and use your one?

**Comment by Le0Developer** [comment]
@test2a
1. create a new issue instead of using an unrelated one
2. no, our api is fundamentally different
