### ISSUE TITLE
Does the plugin work with Playwright?

### ISSUE THREAD

**Issue by galaczi** [NopeCHA/NopeCHA#30]
Hi, does the plugin work with Playwright?

Is there an example how to use it? Either in Puppeteer or Playwright?

**Comment by Jaewan-Yun** [comment]
Yes, it works with playwright

**Comment by galaczi** [comment]
How to use it?

How to load the plugin?
Should I await something in my script?

**Comment by galaczi** [comment]
Ok, so extensions only work in non-headless mode, so that is not good for me. Do you support 2captcha API?

**Comment by Jaewan-Yun** [comment]
Extensions do work if you use the chrome flag to make it headless. For chrome, pass the argument `--headless=chrome`

And yes, our API generates tokens as well.

**Comment by Jaewan-Yun** [comment]
see https://developers.nopecha.com for details

**Comment by galaczi** [comment]
Extensions work only in non-headless mode in Playwright.

https://playwright.dev/docs/chrome-extensions

Do you specifically support the 2captcha API? So I can use puppeteer-extra-plugin-recaptcha?

**Comment by Jaewan-Yun** [comment]
Like I said, extensions work with the new chrome flag.

**Comment by galaczi** [comment]
Got it, thanks! Should I await something in Puppeteer?
