### ISSUE TITLE
Infinite reload

### ISSUE THREAD

**Issue by bremaya** [NopeCHA/NopeCHA#33]
For some reason nopeCHA cannot solve the CAPTCHAS of this site: https://apkadmin.com, just getting into an infinite loop.

**Comment by Jaewan-Yun** [comment]
They're using Cloudflare Turnstile which we do not support in our extension. We are working on a Token API for Turnstile, so stay tuned for announcements.

**Comment by bremaya** [comment]
Ok, thanks for the update.  👍🏽💪🏽❤️🇧🇷

Em ter., 6 de dez. de 2022 18:04, Jaewan Yun ***@***.***>
escreveu:
